name: "Feature request"
description: Suggest an improvement or new feature for EdgeGPT
labels: [ "enhancement" ]
body:
  - type: textarea
    id: Description
    attributes:
      label: Describe the enhancement
      description: A clear and concise description of what you want to be implemented.
      placeholder: Enhancement description
    validations:
      required: true
  - type: textarea
    id: Context
    attributes:
      label: Additional Context
      description: If applicable, please provide any extra information, external links, or screenshots that could be useful.
      placeholder: Additional info
    validations:
      required: false
